services:
    sylake_akeneo_producer.publish_attribute_step:
        class: %pim_connector.step.item_step.class%
        public: false
        arguments: [publish_product_step, '@event_dispatcher', '@akeneo_batch.job_repository', '@pim_connector.reader.database.product', '@pim_connector.processor.normalization.product', '@sylake_akeneo_producer.connector.writer.rabbit_mq.product']
    sylake_akeneo_producer.publish_attribute_option_step:
        class: %pim_connector.step.item_step.class%
        public: false
        arguments: [publish_group_step, '@event_dispatcher', '@akeneo_batch.job_repository', '@pim_connector.reader.database.group', '@pim_connector.processor.normalization.group', '@sylake_akeneo_producer.connector.writer.rabbit_mq.group']
    sylake_akeneo_producer.publish_association_type_step:
        class: %pim_connector.step.item_step.class%
        public: false
        arguments: [publish_family_step, '@event_dispatcher', '@akeneo_batch.job_repository', '@pim_connector.reader.database.family', '@pim_connector.processor.normalization.family', '@sylake_akeneo_producer.connector.writer.rabbit_mq.family']
    sylake_akeneo_producer.publish_category_step:
        class: %pim_connector.step.item_step.class%
        public: false
        arguments: [publish_category_step, '@event_dispatcher', '@akeneo_batch.job_repository', '@pim_connector.reader.database.category', '@pim_connector.processor.normalization.category', '@sylake_akeneo_producer.connector.writer.rabbit_mq.category']
    sylake_akeneo_producer.publish_family_step:
        class: %pim_connector.step.item_step.class%
        public: false
        arguments: [publish_association_type_step, '@event_dispatcher', '@akeneo_batch.job_repository', '@pim_connector.reader.database.association_type', '@pim_connector.processor.normalization.association_type', '@sylake_akeneo_producer.connector.writer.rabbit_mq.association_type']
    sylake_akeneo_producer.publish_group_step:
        class: %pim_connector.step.item_step.class%
        public: false
        arguments: [publish_attribute_option_step, '@event_dispatcher', '@akeneo_batch.job_repository', '@pim_connector.reader.database.attribute_option', '@pim_connector.processor.normalization.attribute_option', '@sylake_akeneo_producer.connector.writer.rabbit_mq.attribute_option']
    sylake_akeneo_producer.publish_product_step:
        class: %pim_connector.step.item_step.class%
        public: false
        arguments: [publish_attribute_step, '@event_dispatcher', '@akeneo_batch.job_repository', '@pim_connector.reader.database.attribute', '@pim_connector.processor.normalization.attribute', '@sylake_akeneo_producer.connector.writer.rabbit_mq.attribute']
    sylake_akeneo_producer.connector.job:
        class: %pim_connector.job.simple_job.class%
        tags:
        - { name: akeneo_batch.job, connector: 'AkeneoProducerBundle connector', type: '%pim_connector.job.export_type%' }
        arguments: [sylake_akeneo_producer, '@event_dispatcher', '@akeneo_batch.job_repository', ['@sylake_akeneo_producer.publish_product_step', '@sylake_akeneo_producer.publish_group_step', '@sylake_akeneo_producer.publish_family_step', '@sylake_akeneo_producer.publish_category_step', '@sylake_akeneo_producer.publish_association_type_step', '@sylake_akeneo_producer.publish_attribute_option_step', '@sylake_akeneo_producer.publish_attribute_step']]
    sylake_akeneo_producer.connector.job_parameters:
        class: Sylake\AkeneoProducerBundle\Connector\JobParameters\AkeneoProducer
        tags:
        - { name: akeneo_batch.job.job_parameters.default_values_provider }
        - { name: akeneo_batch.job.job_parameters.constraint_collection_provider }
        lazy: true
        arguments: ['@pim_connector.job.job_parameters.default_values_provider.product_csv_export', '@pim_connector.job.job_parameters.constraint_collection_provider.product_csv_export', [sylake_akeneo_producer], '%sylake_akeneo_producer.config.locales%']
    sylake_akeneo_producer.pim_job_instance_sylake_akeneo_producer:
        class: %pim_enrich.provider.form.job_instance.class%
        tags:
        - { name: pim_enrich.provider.form }
        arguments: [{ sylake_akeneo_producer: pim-job-instance-sylake-akeneo-producer }]
    sylake_akeneo_producer.connector.writer.rabbit_mq.attribute:
        class: Sylake\AkeneoProducerBundle\Connector\Writer\RabbitMqItemWriter
        public: false
        arguments: ['@old_sound_rabbit_mq.sylake_producer', akeneo_attribute_updated]
    sylake_akeneo_producer.connector.writer.rabbit_mq.attribute_option:
        class: Sylake\AkeneoProducerBundle\Connector\Writer\RabbitMqItemWriter
        public: false
        arguments: ['@old_sound_rabbit_mq.sylake_producer', akeneo_attribute_option_updated]
    sylake_akeneo_producer.connector.writer.rabbit_mq.association_type:
        class: Sylake\AkeneoProducerBundle\Connector\Writer\RabbitMqItemWriter
        public: false
        arguments: ['@old_sound_rabbit_mq.sylake_producer', akeneo_association_type_updated]
    sylake_akeneo_producer.connector.writer.rabbit_mq.product:
        class: Sylake\AkeneoProducerBundle\Connector\Writer\RabbitMqItemWriter
        public: false
        arguments: ['@old_sound_rabbit_mq.sylake_producer', akeneo_product_updated]
    sylake_akeneo_producer.connector.writer.rabbit_mq.category:
        class: Sylake\AkeneoProducerBundle\Connector\Writer\RabbitMqItemWriter
        public: false
        arguments: ['@old_sound_rabbit_mq.sylake_producer', akeneo_category_updated]
    sylake_akeneo_producer.connector.writer.rabbit_mq.family:
        class: Sylake\AkeneoProducerBundle\Connector\Writer\RabbitMqItemWriter
        public: false
        arguments: ['@old_sound_rabbit_mq.sylake_producer', akeneo_family_updated]
    sylake_akeneo_producer.connector.writer.rabbit_mq.group:
        class: Sylake\AkeneoProducerBundle\Connector\Writer\RabbitMqItemWriter
        public: false
        arguments: ['@old_sound_rabbit_mq.sylake_producer', akeneo_group_updated]
