extensions:
    pim-job-instance-sylake-akeneo-producer-edit:
        module: pim/form/common/edit-form

    pim-job-instance-sylake-akeneo-producer-edit-cache-invalidator:
        module: pim/cache-invalidator
        parent: pim-job-instance-sylake-akeneo-producer-edit
        position: 1000

    pim-job-instance-sylake-akeneo-producer-edit-tabs:
        module: pim/form/common/form-tabs
        parent: pim-job-instance-sylake-akeneo-producer-edit
        targetZone: content
        position: 100

    pim-job-instance-sylake-akeneo-producer-edit-properties:
        module: pim/job/common/edit/properties
        parent: pim-job-instance-sylake-akeneo-producer-edit-tabs
        aclResourceId: pim_importexport_export_profile_property_edit
        targetZone: container
        position: 100
        config:
            tabTitle: pim_enrich.form.job_instance.tab.properties.title
            tabCode: pim-job-instance-properties

    pim-job-instance-sylake-akeneo-producer-edit-content:
        module: pim/job/product/edit/content
        parent: pim-job-instance-sylake-akeneo-producer-edit-tabs
        aclResourceId: pim_importexport_export_profile_content_edit
        targetZone: container
        position: 110
        config:
            tabTitle: pim_enrich.form.job_instance.tab.content.title
            tabCode: pim-job-instance-content

    pim-job-instance-sylake-akeneo-producer-edit-history:
        module: pim/common/tab/history
        parent: pim-job-instance-sylake-akeneo-producer-edit-tabs
        targetZone: container
        aclResourceId: pim_importexport_export_profile_history
        position: 120
        config:
            class: Akeneo\Tool\Component\Batch\Model\JobInstance
            title: pim_enrich.form.job_instance.tab.history.title
            tabCode: pim-job-instance-history

    pim-job-instance-sylake-akeneo-producer-edit-properties-code:
        module: pim/job/common/edit/field/text
        parent: pim-job-instance-sylake-akeneo-producer-edit-properties
        position: 100
        targetZone: properties
        config:
            fieldCode: code
            label: pim_enrich.form.job_instance.tab.properties.code.title
            readOnly: true

    pim-job-instance-sylake-akeneo-producer-edit-properties-label:
        module: pim/job/common/edit/field/text
        parent: pim-job-instance-sylake-akeneo-producer-edit-properties
        position: 110
        targetZone: properties
        config:
            fieldCode: label
            label: pim_enrich.form.job_instance.tab.properties.label.title
            readOnly: false

    pim-job-instance-sylake-akeneo-producer-edit-content-structure:
        module: pim/job/product/edit/content/structure
        parent: pim-job-instance-sylake-akeneo-producer-edit-content
        targetZone: structure-filters
        position: 100

    pim-job-instance-sylake-akeneo-producer-edit-label:
        module: pim/job/common/edit/label
        parent: pim-job-instance-sylake-akeneo-producer-edit
        targetZone: title
        position: 100

    pim-job-instance-sylake-akeneo-producer-edit-meta:
        module: pim/job/common/edit/meta
        parent: pim-job-instance-sylake-akeneo-producer-edit
        targetZone: meta
        position: 100

    #    pim-job-instance-sylake-akeneo-producer-edit-back-to-grid:
    #        module: pim/form/common/back-to-grid
    #        parent: pim-job-instance-sylake-akeneo-producer-edit
    #        targetZone: back
    #        aclResourceId: pim_importexport_export_profile_index
    #        position: 80
    #        config:
    #            backUrl: pim_importexport_export_profile_index

    pim-job-instance-sylake-akeneo-producer-edit-delete:
        module: pim/job/export/edit/delete
        parent: pim-job-instance-sylake-akeneo-producer-edit
        targetZone: buttons
        aclResourceId: pim_importexport_export_profile_remove
        position: 100
        config:
            trans:
                title: confirmation.remove.job_instance
                content: pim_enrich.confirmation.delete_item
                success: flash.job_instance.removed
                failed: error.removing.job_instance
            redirect: pim_importexport_export_profile_index

    pim-job-instance-sylake-akeneo-producer-edit-save-buttons:
        module: pim/form/common/save-buttons
        parent: pim-job-instance-sylake-akeneo-producer-edit
        targetZone: buttons
        position: 120

    pim-job-instance-sylake-akeneo-producer-edit-save:
        module: pim/job-instance-export-edit-form/save
        parent: pim-job-instance-sylake-akeneo-producer-edit
        targetZone: buttons
        position: 0
        config:
            redirectPath: pim_importexport_export_profile_show

    pim-job-instance-sylake-akeneo-producer-edit-state:
        module: pim/form/common/state
        parent: pim-job-instance-sylake-akeneo-producer-edit
        targetZone: state
        position: 900
        config:
            entity: pim_enrich.entity.job_instance.title

    pim-job-instance-sylake-akeneo-producer-edit-content-data-help:
        module: pim/job/product/edit/content/data/help
        parent: pim-job-instance-sylake-akeneo-producer-edit-content-data

    pim-job-instance-sylake-akeneo-producer-edit-validation:
        module: pim/job/common/edit/validation
        parent: pim-job-instance-sylake-akeneo-producer-edit

    pim-job-instance-sylake-akeneo-producer-edit-content-data-add-filter:
        module: pim/job/product/edit/content/data/add-select/attribute
        parent: pim-job-instance-sylake-akeneo-producer-edit-content-data
        targetZone: headings
        position: 90
